### ISSUE TITLE
Would be great if you posted a video of spaces-renamer in action

### ISSUE THREAD

**Issue by ryanerwin** [dado3212/spaces-renamer#13]
I was going to install this, but I don't run `mySIMBL` for anything else and I don't like the idea of disabling SIP because over the years I've found adjusting my Mac's configuration much makes upgrades less likely to work correctly. I would love to rename my spaces, but I would like to see a video clip of this in action to see what it actually looks like. Is it ascetically pleasing?

Thanks for releasing something that a lot of us are interested in (renaming our spaces).

**Comment by dado3212** [comment]
I think you can re-enable SIP after you install mySIMBL and the spaces renamer, but I'm not entirely sure.

**Comment by dado3212** [comment]
Here's a video of it in action (and I added the link to the README file as well).  Thanks!
