### ISSUE TITLE
Menubar icon displays a blank menu; appears nonfunctional

### ISSUE THREAD

**Issue by cucumbur** [dado3212/spaces-renamer#14]
So I have spaces renamer and mySimbl, all updated to the newest (stable) version. Same with macOS. I used to rely on TotalSpaces just to rename spaces (I cant believe this isn't a default feature), but figured I would try this out. Here is the app in my menu:
<img width="587" alt="screenshot 2018-04-13 00 49 37" src="https://user-images.githubusercontent.com/8746469/38723091-dfa78ef8-3eb4-11e8-85c8-7c4d0326be95.png">

However, when I click it or try basically any troubleshooting i.e. killing the dock or restarting, I just get this:
<img width="378" alt="screenshot 2018-04-13 00 38 03" src="https://user-images.githubusercontent.com/8746469/38723093-dfbbcc74-3eb4-11e8-98b4-fc6ff898c534.png">

I am new to all this, so my best guess is that maybe I need to toggle AMFI to get it to work? However, I haven't seen it listed as a prerequisite anywhere, and I have read that it's best to avoid it unless you need to toggle it.
<img width="284" alt="screenshot 2018-04-13 00 49 47" src="https://user-images.githubusercontent.com/8746469/38723090-df75c882-3eb4-11e8-851d-f39b9e44f13a.png">

Is AMFI in need of toggling or is there some other issue at play here, most likely? Thats what I am trying to figure out.

**Comment by cucumbur** [comment]
Or my dumb ass misread the SIP and AMFI icons as the opposite and I need to disable SIP. That may be it...

**Comment by newgoliath** [comment]
I have the same problem.  Rebooted with Command-R, opened a terminal, csrutil disable, csrutil status (output disabled); reboot.  

I see the same thing you do.

Any help would be grand.

**Comment by dado3212** [comment]
If you create a new space, does it work then?

**Comment by dado3212** [comment]
Can you tell me what files exist in ~/Library/Containers/com.alexbeals.spacesrenamer?

**Comment by ryanerwin** [comment]
**PROGRESS** I was getting the same blank menu bar that @cucumbur and @newgoliath posted about, but as @dado3212  hinted about a path, I checked and that folder didn't exist. I manually created `~/Library/Containers/com.alexbeals.spacesrenamer`.

**WORKING** That got the blank menu bar working, but renaming spaces still didn't work. When I opened mySIMBL, under `System Info` -> `Apple Mobile File Integrity (AMFI)` RED. I Toggled AMFI (turning it green). Then did my `killall -9 Dock` and restarted `SpacesRenamer` and now I'm renaming some spaces :-)

![image](https://user-images.githubusercontent.com/2156415/38792937-d1017d62-4181-11e8-9cde-274ac2ec39c4.png)

### My New Named Spaces..
![image](https://user-images.githubusercontent.com/2156415/38792964-e514ef50-4181-11e8-97a8-0fdd1de0d8f0.png)

**Comment by dado3212** [comment]
@ryanerwin, thanks that helps a lot.  I thought the folder was automatically created, so I'll push an update later today that creates it if it doesn't exist.

**Comment by dado3212** [comment]
@ryanerwin, @newgoliath, @cucumbur, hopefully this fixes this issue. LMK if it does.  v.1.4.0 is the updated version which should address this.
