### ISSUE TITLE
Not working with (top) corners triggers / fullscreen mode

### ISSUE THREAD

**Issue by pointu-l** [dado3212/spaces-renamer#18]
Hello,

In first time thanks you for spaces-renamer ! A great tool.

I noticed you're plugin no working when desktop thumbnails are already visible during mission control invocation. If you use an top active corner or invoke mission control from a fullscreen app, you will see "Desktop 1" etc.

I just put theses lines :
```swift
        if (unexpandedViews == nil)
        {
            if (expandedViews == nil)
            {
                return;
            }
            unexpandedViews = expandedViews;
        }
```
After 
```swift
        NSArray<CALayer *> *unexpandedViews = self.sublayers[3].sublayers[0].sublayers;
        NSArray<CALayer *> *expandedViews = self.sublayers[3].sublayers[1].sublayers;
```
in the setBounds function for bypass the problem, but It look like very ugly :D 

👍

**Comment by dado3212** [comment]
Oooh good catch!  Let me give this a look and see if I can come up with a good solution.

**Comment by dado3212** [comment]
Alright, this should be fixed.  Thanks for pointing this out!
