### ISSUE TITLE
It doesn't work in High Sierra

### ISSUE THREAD

**Issue by aminta** [dado3212/spaces-renamer#19]
The Spaces are not renamed in High Sierra 10.13.4...

**Comment by dado3212** [comment]
Did you use this on a lower version and it worked?  I'm running High Sierra 10.13.3, and it's working fine.  I suppose it's possible that something changed.  Are other SIMBL tweaks working?

**Comment by dado3212** [comment]
Can you try and install another SIMBL tweak and confirm that it's a problem with Spaces Renamer, and not with your SIMBL installation?

**Comment by aminta** [comment]
Ok, wich one? I have no practice of SIMBL... Thanks!

**Comment by dado3212** [comment]
Any of [w0lfschild](https://github.com/w0lfschild)'s should work, you can find some in the 'Discover' tab of mySIMBL.  Also, make sure you're on the most updated version (the 'About' tab in mySIMBL).  It should be 0.7.1 right now.

**Comment by aminta** [comment]
I've tried some other tweaks, like biniventory, and they work! But Spaces Renamer doesn't :-(  I'm on mySIMBL 0.7.1 and I'm running Spaces Renamer 1.4.1.

**Comment by aminta** [comment]
Updated to High Sierra 10.13.5, same problem...

**Comment by annabechang** [comment]
Hi, thank you for such a great program. I am having the same issue as @aminta. I have the program running, I named them and clicked update names, but the names of my multi-screens are still the same.

**Comment by dado3212** [comment]
I'm running High Sierra 10.13.5, and it's working correctly. @aminta and @annabechang can you let me know if `~/Library/Containers/com.alexbeals.spacesrenamer` exists on your computer?  And if not, can you create it?

**Comment by FlorianLiebhart** [comment]
@aminta @annabechang @dado3212 
I had the same problem on OSX 10.12.6.
I found the problem, and two possible solutions:

Problem: Clicking "Update Names" within the Spaces Renamer had no effect. 
Cause: I had an outdated version of mySIMBL (0.2.x) and it would not let me update to a newer version during the install update process. 

Solution:
#1 (not recommended)
Changing the ownership of mySIMBL.app to the root user:
Open Terminal and type: sudo chown -Rv root mySIMBL.app
Now clicking "Update Names" within Spaces Renamer will have an effect.

#2 (better)
Update mySIMBL by directly going here 
https://github.com/w0lfschild/mySIMBL/releases/latest
Download & install it. Then Spaces Renamer will also work properly.

And remember to disable System Integrity Check first:
Restart the mac with holding Option+R to open the Recovery Setup. Open Terminal from the Menu bar and type "csrutil disable". Then restart.

Best,
Florian

**Comment by dado3212** [comment]
@FlorianLiebhart Thanks!  I caught that I was linking to an older version in the release instructions, but I forgot I had a link in the README as well.  Good catch!  I've also run into an error once where it wasn't working, but started working again after running `killall -9 Dock` again from Terminal, so try that as another option.

**Comment by dotjay** [comment]
Sadly, this doesn't work for me no matter what I try (as per recommendations above).

**Comment by blake-regalia** [comment]
Doesn't seem to work no matter what in 10.13.5

**Comment by codycodes** [comment]
Will post in other issue but also wanted to say I'm in Mojave beta and the above didn't work for me.

**Comment by GijsMulders** [comment]
I got it to work following the instructions from FlorianLiebhart.

What did it for me was disabling SIP by rebooting into recovery mode *before* installing mySIMBL, then following the installation instructions for spaces renamer.

Now I can rename my spaces :)

**Comment by codycodes** [comment]
I'm running other SIMBL tweaks too and followed the above instructions as best I could ^. Some have commented that they're able to get it to work and others not. Would like to know if I'm missing anything to make this work, or it's just not working on later versions of High Sierra and now Mojave.

**Comment by dado3212** [comment]
I'm on 10.13.6 now, and it's still working for me.  Not sure how to replicate it :/

**Comment by aminta** [comment]
I confirm that is working for me also on 10.13.6, thanks!

**Comment by dado3212** [comment]
Closing!  For anyone else who comes across this issue, make sure that you've disable SIP (`csrutil disable` while in Recovery mode), and that you're running the most recent version (and that the app is set to start on login!)
