### ISSUE TITLE
Dock crashes when I swipe up with four fingers

### ISSUE THREAD

**Issue by Patrik-svobodik** [dado3212/spaces-renamer#21]

**Comment by dado3212** [comment]
I can't replicate this.  What version of spaces-renamer and mySIMBL are you running?

**Comment by jkmartindale** [comment]
On my first installation I found that opening Mission Control would cause Dock to crash if I used a hot corner or F3 (hadn't tested any other way). Once I opened the Spaces Renamer app and renamed a few spaces, everything became stable. Hope this helps.

spaces-renamer: 1.4.1
mySIMBL: 0.7.1 (71)

**Comment by dado3212** [comment]
I fixed the bug where Dock crashes if no name has been renamed yet, so this should be fixed.  Closing, open a new issue if anyone else encounters this issue.
