### ISSUE TITLE
Max 14 desktops

### ISSUE THREAD

**Issue by visicode** [dado3212/spaces-renamer#22]
Max 14 desktops

**Comment by dado3212** [comment]
Yeah...are you really using a mac with more than 14 desktops?  I could probably make it wrap on a different line if you're hitting visual limits on the width of your screen.  Lemme know if you're actually running into this problem, or you just made a bunch of desktops to test.

**Comment by visicode** [comment]
Haha, yes, I'm at the maximum, 16 desktops 😅
I have 1 desktop for each purpose (different works, home, health, pleasure, …) and your tool helps me a lot to recognize them

**Comment by dado3212** [comment]
Should be fixed in v1.4.2, just pushed.
