### ISSUE TITLE
Mojave 10.14, Worked initially..now no longer..

### ISSUE THREAD

**Issue by drewauff** [dado3212/spaces-renamer#23]
**Describe the bug**

The App. runs just fine but after the first reboot after using it, it now no longer renames spaces.

Needs Mojave 10.14 support..

**Versions**
1. MySIMBL version - 0.7.1 (71)
2. Spaces Renamer version - v1.4.1-1

**Comment by codycodes** [comment]
Same version for MySIMBL and Spaces Renamer, same issue. Menu bar app loads no problem, but won't update names of spaces.

**Comment by drewauff** [comment]
For whatever reason (I really have no idea why) work perfectly on Mojave beta 4.

The only issue I have is renaming spaces occupied by fullscreen apps ie.iTerm, I can rename but does not always stick.

Also, would like to be able to hide the menubar icon via Bartender 3. A hotkey would also be great.

**Comment by codycodes** [comment]
@drewauff Definitely a workaround and a keyboard shortcut would be great, but you could use bartender 3's search functionality to search for spacesrenamer and then hit enter twice to invoke it. +1 to being able to hide in Bartender. Haven't updated to beta 4 yet but will do so and report back.

**Comment by codycodes** [comment]
I'm still having issues on beta 4 (18A336e) I believe. Haven't gotten this functionality to work yet. Other SIMBL plugins are working as expected (cdock, afloat, clear all for notification center, etc.)

**Comment by codycodes** [comment]
Still having this issue after updating to 10.14 Beta (18A347e). Other SIMBL apps still working normally 😁.

**Comment by drewauff** [comment]
Yeah, nothing changed after beta 5...

Also FWIW, through a little experimentation, I found that I can change the spaces names, invoke "update names" and exit the app and the names still persist.. I guess this will have to do for now.I MIGHT write an apple script to make this a little friendlier..will see, no promises :).

**Comment by dado3212** [comment]
@drewauff what do you mean re: your most recent experimentation?

**Comment by dado3212** [comment]
Also, in what sense for the keyboard shortcut?  Are there other applications that do that?  I thought for that to be an option you would have to listen to every single keyboard press, which would require some System Preferences Accessibility toggles, and a questionable ability to add to the app.

**Comment by nrcarnevali** [comment]
Hi,

So I just recently installed and I am on Mojave 10.14 Beta (18A384a) and I can the program in the top tray, type in names for the spaces, click updates, and then the names don't change. I cannot comment if this ever worked on my laptop though as I just found this app a few days ago.

Thanks For All Your Hard Work!

**Comment by dado3212** [comment]
@nrcarnevali Does this directory exist `/Users/<username>/Library/Containers/com.alexbeals.SpacesRenamer`, and does it have two .plists in it, `currentspaces` and `spacesrenamer`?  If so, can you paste the contents of them on pastebin and share the link here?  It's possible the rendering changed on 10.14, but I don't have a spare computer to load the beta onto right now.

**Comment by nrcarnevali** [comment]
Worked great although your example to disable SIP didn't work. It said "csrutil disable this tool needs to be executed from the recovery os". So I just booted CMD +R and ran it from that terminal window.

Thanks!

**Comment by dado3212** [comment]
Yeah, you need to do it in Recovery mode.  That was included in the tutorial I linked, but I'll make it a little clearer.  Thank you!
