### ISSUE TITLE
spaces name length limit at 4

### ISSUE THREAD

**Issue by defims** [dado3212/spaces-renamer#24]
![2018-07-23 15 35 36](https://user-images.githubusercontent.com/767580/43063377-34e96b1a-8e8e-11e8-84ca-da3035abaf2b.png)
![2018-07-23 15 35 48](https://user-images.githubusercontent.com/767580/43063387-39aede6e-8e8e-11e8-9539-1720d555add9.png)
![2018-07-23 15 36 07](https://user-images.githubusercontent.com/767580/43063395-3d1b63b0-8e8e-11e8-8dce-459a8cc775b4.png)

**Comment by dado3212** [comment]
Unfortunately, I have absolutely no idea how to resize the name labels in a reliable fashion.  In my testing, the label max is around 8 characters.  Not sure why it's cutting at what looks like 4 given that you have others with 6 characters that are displaying fine.

**Comment by dado3212** [comment]
Hey @defims!  Said I wouldn't fix this, but I just did!  v1.6.0 has no size limit, and should handle longer space names (though they'll be cropped in the expanded view at around 24 characters).
