### ISSUE TITLE
Menubar window too small when only one space is open

### ISSUE THREAD

**Issue by w0lfschild** [dado3212/spaces-renamer#27]
**Describe the bug**

When only one space is open the window to rename spaces is too small.

<img width="282" alt="screen shot 2018-08-12 at 10 17 11 am" src="https://user-images.githubusercontent.com/1920148/44004827-27663b04-9e1e-11e8-97a3-f8c7fadad9e0.png">

**Versions**
1. macOS version - 10.14 Beta (18A353d)
2. Spaces Renamer version - 1.4.2

**Comment by dado3212** [comment]
Should be fixed as of v1.5.0.  Missed this in modifying the autolayout constraints change, thanks for pointing it out!
