### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by w0lfschild** [dado3212/spaces-renamer#3]
-  `_CD_CLASS_NAME_` Swizzles should be changed to something else otherwise this won't work simultaneously with cDock. Maybe use _HDM or _SR.

- `Spaces Renamer` doesn't work properly for Spaces on different displays.
	- The names apply in the same order on all displays as the names of the main display
	- The Desktops are not shown in the menubar app
 

- There is no way to quit the `Spaces Renamer` menubar app.

**Comment by dado3212** [comment]
The _CD swizzle and the lack of a quit option are fixed in #6.  I'm going to mark this issue as closed, and open a new one for the display issue for easier tracking.
