### ISSUE TITLE
Access spaces' names

### ISSUE THREAD

**Issue by alextechtai** [dado3212/spaces-renamer#31]
Is there any way to access the names of the spaces? I'm trying use this with up [TextBar](http://richsomerfield.com/apps/textbar/) Hoping I could get the space name to display in status bar.

**Comment by dado3212** [comment]
~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.plist contains the naming mapping from space UUID to name.

~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist contains the current spaces and their ordering.

My renamer does some educated guesswork for multiple monitor detection, so it can usually properly pair them.  I looked into adding the space name to the status bar in issue #5 but there was no way in macOS to differentiate the status bar between monitors, so it broke multi-monitor support.  I'm curious if TextBar found a way around that.
