### ISSUE TITLE
misson control is at bottom..

### ISSUE THREAD

**Issue by iromise** [dado3212/spaces-renamer#32]
**Describe the bug**
Just as the Title shows. My Macos Version 10.13.6 (17G65).
**Versions**
1. MySIMBL version - newest.
2. Spaces Renamer version - newest.

And besides, the rename do not work.

**Comment by dado3212** [comment]
What do you mean by this?  Can you show me a picture?

**Comment by iromise** [comment]
Just like this...
No Available Window is because I Hide all the window.
<img width="594" alt="jietu20181127-133129" src="https://user-images.githubusercontent.com/11772027/49060538-ef3b2d00-f248-11e8-87f7-dd29103ee742.png">

**Comment by dado3212** [comment]
Do you have any other SIMBL tweaks installed?  If you uninstall my tweak, this stops happening?

**Comment by iromise** [comment]
Yeah, I only have the one you provide.

**Comment by dado3212** [comment]
Is the renaming still not working?

**Comment by iromise** [comment]
No.

**Comment by iromise** [comment]
anything going on?

**Comment by dado3212** [comment]
Can you check if `~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.plist` and `~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist` exist, and paste their contents if they do?

Sorry re: delay, this is a hobby project so it's not high in priority.

**Comment by iromise** [comment]
oh, I am so sorry..
this is the content


[com.alexbeals.spacesrenamer.currentspaces.txt](https://github.com/dado3212/spaces-renamer/files/2635520/com.alexbeals.spacesrenamer.currentspaces.txt)
[com.alexbeals.spacesrenamer.txt](https://github.com/dado3212/spaces-renamer/files/2635521/com.alexbeals.spacesrenamer.txt)

**Comment by iromise** [comment]
yeah, I have two monitors, one is macos, the other is dell.  I have tried, but it does not work...

**Comment by Sn0wl3r0ker** [comment]
seems like it doesn't work on mojave? mine doesn't work... : ( will you update it?

**Comment by dado3212** [comment]
@Sn0wl3r0ker are you getting the same bug?  I'm on Mojave on multiple computers, and can't repro it.

**Comment by alextechtai** [comment]
@Sn0wl3r0ker @iromise So I think I ran into the same problem just now. For some reason my spaces just refuse to get renamed. What I did was I followed @dado3212's suggestion to remove both mySIMBL and Spaces Renamer and downloaded them again. It worked pretty well afterwards. Make sure you don't forget to run the kill dock command.

**Comment by iromise** [comment]
@alextechtai sorry, i try again, but I still cannot do it..

**Comment by alextechtai** [comment]
@iromise Did you run `killall -9 Dock` and also check **Accessibility** in settings for the permissions?

**Comment by iromise** [comment]
yes, I have already run. And what do you mean by the permission? i have checked the `System Preferences" > "Users & Groups" > "Login Items`. 

when i try to change the space name, it does work..

**Comment by alextechtai** [comment]
@iromise I'm not sure then... 😭

**Comment by iromise** [comment]
@alextechtai  anyway, thank you very much.

**Comment by dubslaff** [comment]
First thanks @dado3212 that you took the initiative to solve this "long-standing open problem" within mission control. 

Unfortunately, it does not work neither in my case and does not rename anything. Also here the plist-files are in place and contain the names I specified in the menu. Other mySIMBL-plugins work perfectly, I deactivated SIP and AMFI, reinstalled several times. I am on the most recent version of Mojave (10.14.3) on 2015 Macbook Pro 13" and checked it with several display configurations (internal, one external, two external). Logs in debug mode after pressing "Update Names" show imho nothing special (except the SpacesRenamer actions like the "looked up value" etc.). I can send you the logs if needed.

**Comment by dado3212** [comment]
@dubslaff can you make a new issue if your issue is not mission control appearing at the bottom?

**Comment by dado3212** [comment]
@iromise Is this still reproing?

**Comment by iromise** [comment]
I am sorry that recently I do not use it.

**Comment by dado3212** [comment]
I'm going to close the issue for now, but if anyone else runs into this, please open a new one!
