### ISSUE TITLE
Spaces Renamer not working on Mojave 10.14.3

### ISSUE THREAD

**Issue by dubslaff** [dado3212/spaces-renamer#33]
**Describe the bug**
First thanks @dado3212 that you took the initiative to solve this "long-standing open problem" within mission control.

Unfortunately, it does not work neither in my case and does not rename anything. Also here the plist-files are in place and contain the names I specified in the menu. Other mySIMBL-plugins work perfectly, I deactivated SIP and AMFI, reinstalled several times. I am on the most recent version of Mojave (10.14.3) on 2015 Macbook Pro 13" and checked it with several display configurations (internal, one external, two external). Logs in debug mode after pressing "Update Names" show imho nothing special (except the SpacesRenamer actions like the "looked up value" etc.). I can send you the logs if needed.

**Versions**
1. MySIMBL version - 0.7.2 (72)
2. Spaces Renamer version - 1.6.0

**Comment by dubslaff** [comment]
Ok, I found out why it did not work. I had the "reduce transparency" enabled in the Accessibility settings, as the system feels snappier then. However, this hinders Space Renamer to function. When I untick this setting, it works as it should. Maybe you can take a brief look into it and integrate this compatibility in the next versions? Thanks!

**Comment by supercgeek** [comment]
Weird, I have the exact opposite issue. I can only see my spaces bar (with space renamer enabled) when I have reduce transparency enabled.

**Comment by dado3212** [comment]
@supercgeek Out of curiosity, do you have any other Accessibility settings turned on?  Or any other display tweaks?

**Comment by dado3212** [comment]
Merging this into the more specific issue.

**Comment by dado3212** [comment]
This should be fixed in v1.7.0.  If that doesn't resolve the problem, please open a new task!
