### ISSUE TITLE
10.11 El Capitan compatibility? The last build to support?

### ISSUE THREAD

**Issue by GJRobert** [dado3212/spaces-renamer#34]
As far as I have tested, both 1.3.1 and 1.6.0 contain the app which requires at least macOS 10.12. I would like to know is there an earlier version which works on 10.11?

**Comment by dado3212** [comment]
Does this not work on macOS 10.11?  I'm not entirely sure.  I no longer have a device on 10.11, so I can't add compatibility if it doesn't exist currently.

**Comment by GJRobert** [comment]
My macOS 10.11 won't allow me to open the Space Renamer app, saying it only supports 10.12+. Pity...

**Comment by dado3212** [comment]
This should be fixed in v1.7.0.  If that doesn't resolve the problem, please open a new task!

**Comment by GJRobert** [comment]
Finally I have got time to test 1.7.1 on my El Capitan. It works like a charm. Loving this tool~~~
Thank you!!!
