### ISSUE TITLE
Space names disappear when on focus with many desktops

### ISSUE THREAD

**Issue by dubslaff** [dado3212/spaces-renamer#35]
**Describe the bug**
When many desktops are active and the screen is too small (e.g., internal display), then macOS shrinks the miniature sizes on the top in mission control. When hovering over these miniatures, the names of the spaces other than in focus disappear.

**Versions**
1. MySIMBL version - 0.7.2
2. Spaces Renamer version - 1.6.0

**Comment by dado3212** [comment]
![image](https://user-images.githubusercontent.com/8919256/53972484-c0d4b580-40b3-11e9-9705-38f3920398f6.png)

Presumably you're talking about this behavior, where it only shows the name of the one that is hovered.  This is stock macOS behavior, not something that's affected by SpacesRenamer.  This is out of the scope of this tweak, won't be changing that.
