### ISSUE TITLE
Program only works when turning off transparency

### ISSUE THREAD

**Issue by rockmanvnx6** [dado3212/spaces-renamer#36]
**Describe the bug**
The names only work when I turn off transparency. I don't mind having transparency but still prefer without transparency for the look.

I'm using MacOS high sierra 10.13.5

**Versions**
1. MySIMBL version - 0.7.0
2. Spaces Renamer version - 1.6.0

**Comment by dado3212** [comment]
This should be fixed in v1.7.0.  If that doesn't resolve the problem, please open a new task!
