### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by dominiklohmann** [dado3212/spaces-renamer#37]
I'm interested in some of your code, but it is currently unlicensed and thus unusable for everyone. I think an MIT type license would be a good fit for this project, such that people can use the code when attributing you as the original author.

Please consider—it would be very much appreciated.

**Comment by dado3212** [comment]
If you submit a pull request adding an MIT license, I’ll approve it!  Might not get around to it myself for a little while.
