### ISSUE TITLE
Update Names not working

### ISSUE THREAD

**Issue by coball2** [dado3212/spaces-renamer#39]
I installed the newest versions of MySIMBL and Spaces Renamer on 07/26/2019. I followed all of the steps: installing MySIMBL and SpacesRenamer, along with disabling SIP (also note that I am on Mojave 10.14.5).  After following all of the steps, I logged out and back in; and everything worked great! The ability to name spaces was incredible in improving my productivity--huge thank you!!

But, I restarted my MacBook this morning 07/29/2019 and SpaceRenamer stopped working properly. On restart, all of the spaces launched but they defaulted to native Desktop 1, Desktop 2, Desktop 3, etc. I clicked the SpacesRenamer icon in the menubar, all of the names I had previously inputted remained which was great. I clicked the Update Names button hoping it would rename everything but it didn't work. I tried closing all of the open Desktops except Desktop 1 and re-adding them, and again clicking Update Names with the hope this might fix the solution but it didn't work. I tried quitting SpaceRenamer and relaunching, this also didn't fix the issue.

Can you please kindly assist me in trouble shooting this? I am incredibility grateful I found this tool and I'd really hate to lose the ability to use it now that I've experienced how helpful it is to my workflow.

**Versions**
1. MySIMBL version - 0.7.1 (71)
2. Spaces Renamer version - newest version

**Comment by dado3212** [comment]
Does running `pkill -9 Dock` from Terminal resolve the issue?

**Comment by coball2** [comment]
> Does running `pkill -9 Dock` from Terminal resolve the issue?

It does not.

**Comment by coball2** [comment]
Hello, any chance you can please kindly assist with further troubleshooting?

**Comment by dado3212** [comment]
Can you check the following?

1. `csrutil status`, and let me know what it outputs.
2. Confirm that the Spaces Renamer is in the green state for MySIMBL, and it is running 1.6.1.
3. Can you paste the outputs of `cat ~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.plist` and `cat ~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist`

Thank you!

**Comment by coball2** [comment]
> Can you check the following?
> 
> 1. `csrutil status`, and let me know what it outputs.
> 2. Confirm that the Spaces Renamer is in the green state for MySIMBL, and it is running 1.6.1.
> 3. Can you paste the outputs of `cat ~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.plist` and `cat ~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist`
> 
> Thank you!

Thanks for your reply. Wasn't 100% sure how I was supposed to pull the outputs in question 3, sorry but don't know what you mean by "cat." But I searched the url and located some files, I copied/pasted the text from the files below.

1. disabled
2. Green and running 1.7.1
3. <PLIST> past below:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>spaces_renaming</key>
	<dict>
		<key>281E683D-AF24-4BA4-A18B-AA5EF3E97536</key>
		<string>MAIN</string>
		<key>63C49F5A-C05F-4462-822F-57311AC8C2DA</key>
		<string>Test 3</string>
		<key>EBD8E952-281F-487F-A409-3F99A3516A9D</key>
		<string>Test 2</string>
	</dict>
</dict>
</plist>

3. <current paces.PLIST> past below:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Monitors</key>
	<array>
		<dict>
			<key>Current Space</key>
			<dict>
				<key>ManagedSpaceID</key>
				<integer>4</integer>
				<key>id64</key>
				<integer>4</integer>
				<key>type</key>
				<integer>0</integer>
				<key>uuid</key>
				<string>281E683D-AF24-4BA4-A18B-AA5EF3E97536</string>
			</dict>
			<key>Display Identifier</key>
			<string>23C3B0D7-A911-CF00-FAEA-4DB47B1571C0</string>
			<key>Spaces</key>
			<array>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>4</integer>
					<key>id64</key>
					<integer>4</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string>281E683D-AF24-4BA4-A18B-AA5EF3E97536</string>
				</dict>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>5</integer>
					<key>id64</key>
					<integer>5</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string>EBD8E952-281F-487F-A409-3F99A3516A9D</string>
				</dict>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>6</integer>
					<key>id64</key>
					<integer>6</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string>63C49F5A-C05F-4462-822F-57311AC8C2DA</string>
				</dict>
			</array>
		</dict>
	</array>
</dict>
</plist>

**Comment by dado3212** [comment]
Closing this due to a lack of activity.  Please try with MacForge, and the newest version of the app, and lmk if you're still having this issue.
