### ISSUE TITLE
Names reset following lock unlock

### ISSUE THREAD

**Issue by dado3212** [dado3212/spaces-renamer#4]
I think the space UUID resets.  Not entirely sure how to save through this.  If the computer doesn't know it's the same space, how could I?

**Comment by raarts** [comment]
I'm not an expert at all, but you'll be on the same space as before the lock/unlock?

**Comment by dado3212** [comment]
I think that I misdiagnosed this, and should be partially addressed by #10.  Going to close the issue, but can reopen a similar one if this issue still crops up.
