### ISSUE TITLE
Menubar Display not showing properly in dark mode 10.15

### ISSUE THREAD

**Issue by w0lfschild** [dado3212/spaces-renamer#40]
**Describe the bug**
Not sure if this is isolated to 10.15 or not but that's what I'm running.

Only happens when system is in dark mode.

Issue not present in 1.6.0

<img width="510" alt="Screen Shot 2019-08-05 at 8 35 58 PM" src="https://user-images.githubusercontent.com/1920148/62509721-175c3200-b7c1-11e9-99d4-c7da72e88fad.png">

**Versions**
1. MySIMBL version - 
2. Spaces Renamer version - 1.7

**Comment by dado3212** [comment]
Should be fixed in v1.7.1, lmk if that doesn't resolve the issue.
