### ISSUE TITLE
Can I install MacForge instead of mySIMBL?

### ISSUE THREAD

**Issue by joshuarobs** [dado3212/spaces-renamer#45]
On the mySIMBL GitHub page, it says its been replaced by MacForge. Can I use that instead since it seems like it will be getting updates (into Catalina)?

Thanks

**Comment by dado3212** [comment]
Most likely yes, though I haven’t checked compatibility.  Can you comment if it works?

**Comment by w0lfschild** [comment]
@joshuarobs 

Yes you can use MacForge and if you have the latest version installed you can get Spaces-Renamer here: [LINK](https://www.macenhance.com/mflink?macforge://github.com/w0lfschild/macplugins/raw/master/com.alexbeals.SpacesRenamer)

**Comment by alextechtai** [comment]
@w0lfschild @joshuarobs Does this work on Catalina? I have updated and wanted to check before I do anything

**Comment by w0lfschild** [comment]
@alextechtai yes Spaces-Renamer and MacForge work on Catalina.

**Comment by dado3212** [comment]
Marking this as closed, will update the install directions.
