### ISSUE TITLE
Not working in macOS Catalina?

### ISSUE THREAD

**Issue by gabe-santos** [dado3212/spaces-renamer#46]
Is this working in Catalina? It was working in Mojave but I recently updated and it no longer seems to work.

**Comment by QIanGua** [comment]
I got the same  issue in Mojave .

**Comment by mundie1010** [comment]
It worked fine for me in Mojave, but doesn't work in Catalina.

**Comment by w0lfschild** [comment]
Maybe try using [MacForge](https://github.com/w0lfschild/MacForge) instead of mySIMBL.

**Comment by mundie1010** [comment]
Yes! It works for me using MacForge. I'm a happy camper.

**Comment by sachasmart** [comment]
Just looking for any update: does this work on Catalina for anyone?

**Comment by mundie1010** [comment]
Yes, this works fine for me in Catalina, using MacForge instead of mySIMBL.

**Comment by dado3212** [comment]
Yup, marking this as closed. Just use MacForge instead of MySIMBL.  I've updated the install instructions, open a new task if they're confusing/don't work.
