### ISSUE TITLE
Is there a way to run SpacesRenamer without having to run MacForge at startup?

### ISSUE THREAD

**Issue by alextechtai** [dado3212/spaces-renamer#47]
I am currently on macOS Catalina. I don't have MacForge automatically launch at reboot of my Mac, but SpacesRenamer does. When I reboot and while SpacesRenamer is running, the spaces don't get renamed. After I launch MacForge and then quit the MacForge app again, functionality of SpacesRenamer returns. I'm wondering if there is a way to run SpacesRenamer without having to run MacForge at startup.

**Comment by dado3212** [comment]
@w0lfschild 

Thoughts on this?

**Comment by w0lfschild** [comment]
Not sure what @alextechtai  is asking. 

If they're talking about the helper then no, because that's what does the injecting. If they're talking about opening the main app then the answer is yes make sure the helper is set to open at login and that should be all you need to do.

**Comment by dado3212** [comment]
I think the answer is no, you need the helper open.  I'm going to close this, but feel free to reopen a new task with some more details.
