### ISSUE TITLE
Sorry, but this still does not work using MacForge

### ISSUE THREAD

**Issue by sachasmart** [dado3212/spaces-renamer#48]
Hey before I updated to Catalina this application was working perfectly and I loved it to organized work/school desktops. Now since the update, it does not work and I have since gone to MacForge to run the application (originally using MySIMBL). What is happening for me is spaceremover also has an extra desktop to the spaces that I have open (3 spaces open + 1 space that I cannot see). As well, I can't rename any of spaces - they just remain Desktop 1, Desktop 2, etc. 

SIP is disabled. 

![Screen Shot 2019-12-09 at 10 09 44 AM](https://user-images.githubusercontent.com/56313184/70447308-8649e000-1a6c-11ea-81fa-4e2393633ffd.png)
![Screen Shot 2019-12-09 at 10 09 44 AM (2)](https://user-images.githubusercontent.com/56313184/70447309-8649e000-1a6c-11ea-8199-c80197ff4069.png)

**Comment by dado3212** [comment]
As in it thinks you have 4 spaces open on your main monitor, but you only have 3?  Can you try removing the two plist files in `~/Library/Containers/com.alexbeals.spacesrenamer/`

**Comment by sachasmart** [comment]
> As in it thinks you have 4 spaces open on your main monitor, but you only have 3? Can you try removing the two plist files in `~/Library/Containers/com.alexbeals.spacesrenamer/`

Yes, exactly. I deleted the two files. Still have the same problem.

**Comment by w0lfschild** [comment]
@sachasmart 

Are you able to get any other plugins loading with MacForge? My guess is that's probably your actual issue.

Spaces renamer 100% works on the latest version of Catalina.

**Comment by Britlantine** [comment]
Same with me, I can get it to run but the names won't update. I've rebooted and checked instructions. I'm on OS 10.14.6

I have 2 monitors and the number of desktops is correct. 

SIP and AMFI disabled.

**Comment by Britlantine** [comment]
I had had this problem but I removed, rebooted and reinstalled with Mac Forge and now it works.

**Comment by dado3212** [comment]
Marking as closed per the above comments.
