### ISSUE TITLE
Show name of current space instead of the icon in the menubar

### ISSUE THREAD

**Issue by raarts** [dado3212/spaces-renamer#5]
So you don't need to three-finger swipe-up to know where you are.

Of course if #4 isn't fixed that's a total blocker.

**Comment by dado3212** [comment]
Unfortunately, there's no way that I've found to know which space you're currently on.  The `com.apple.spaces.plist` file, which has a current space field only gets updated when you add and remove a space, and hooking into what I am relatively sure are the underlying objects (WVSpace/WVSpaceList) wasn't doing anything.

**Comment by dado3212** [comment]
This should be fixable, actually, following the fix to #8.

**Comment by dado3212** [comment]
I didn't add this in, because the font size is pretty illegible at that scale.  However as of v1.3.0 (#11), when you open it up to choose the proper screen, the one that you're on is selected, so it's easier to initially name them.

**Comment by raarts** [comment]
I have multiple apps which show text in the menu bar (World Clock comes to mind), and it's pretty legible to me, would it be possible to restore that code, and make it optional for those that don't mind?
Also, the menus for each application are also up there, maybe you made it too small?

**Comment by dado3212** [comment]
OH!  I misunderstood, you mean instead of an icon entirely, just the name of the current space.

**Comment by dado3212** [comment]
Unfortunately, this isn't possible, because there's no way to separate the menu bar item for different monitors, so this breaks multi-monitor support.  You're welcome to fork and add it in if you don't use multiple monitors, but I won't be adding it to Spaces Renamer right now.
