### ISSUE TITLE
Not working on OS Catalina after csrutil reenabled

### ISSUE THREAD

**Issue by abgen27** [dado3212/spaces-renamer#50]
**Versions**
1. MySIMBL version - using latest MacForge
2. Spaces Renamer version - using latest spaces-renamer
3. MacOS Catalina version 10.15

I am able to get spaces-renamer to work during the initial install following all steps outlined in the read-me. However, when I reboot my Mac and reenable csrutil it stops functioning. I've done this twice and same result.

Attempt #1: on restart I did csrutil enable
Attempt #2: I tried to follow the instructions on MacForge under the 'System' tab csrutil enable --without fs --without nvram --without debug; nvram boot-args="amfi_get_out_of_my_way=1" but same result. In fac, I got an error message in the recovery terminal stating that nvram wasn't a recognized term (forget exact wording)

Can someone please help me understand what I'm doing wrong?

**Comment by dado3212** [comment]
Yeah, I've been running into this as well, I need to keep it disabled to work.  cc @w0lfschild is there a way that I can change how this is setup to not require `csrutil` to stay disabled on Catalina?  Does all of MacForge need it to stay disabled, or is it just SpacesRenamer?

**Comment by w0lfschild** [comment]
So you need to have **at least**:

`csrutil enable --without debug --without fs`

I think this **might also be required**:

`sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true`

You do **not want**:

`sudo nvram boot-args="amfi_get_out_of_my_way=1"`

You can get rid of the above with:

`sudo nvram boot-args=""`

**Comment by abgen27** [comment]
Thanks for the guidance @w0lfschild. I tried all of your instructions, but it appears that SpacesRenamer still does not work. Further, only the first line of code you suggested (`csrutil enable --without debug --without fs`) worked. See screenshots below for the error messages I received for the other two codes you suggested (I tried all variations).

![IMG_4252](https://user-images.githubusercontent.com/61991221/80180978-cabbbf80-85b8-11ea-8347-bd02a7bd805e.jpg)
![Terminal Errors](https://user-images.githubusercontent.com/61991221/80181259-5897aa80-85b9-11ea-80f0-f2b633b16c29.png)

Please advise. We appreciate your willingness to help.

**Comment by w0lfschild** [comment]
Since you're trying to run the command in recovery mode you automatically have root powers so you would run the commands without sudo, but that command can just be run on a normal boot with sudo.

**Comment by dado3212** [comment]
Marking this as resolved, will update the README with this.
