### ISSUE TITLE
Bug: Spaces not showing if no names are set

### ISSUE THREAD

**Issue by w0lfschild** [dado3212/spaces-renamer#53]
**Describe the bug**
The entire Spaces bar does not show up at all.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1920148/78519080-095b1880-7777-11ea-84fe-7c0724928bf5.gif)

**Versions**
1. MacForge version - 0.14.1
2. Spaces-Renamer version - 1.7.1

**Comment by dado3212** [comment]
Ooh interesting! What visual settings do you have turned on?  It looks like at the very least you're on dark mode, do you have any other settings set that affect the visual settings?  Anything around transparency?

**Comment by w0lfschild** [comment]
@dado3212 

1) Stock install.
2) Issue persists with all _other_ plugins disabled.
3) Issue persists in Light mode.

**Comment by w0lfschild** [comment]
The issue appears to be in:

```objectivec
@implementation _SRECMaterialLayer
- (void)setFrame:(CGRect)arg1 {
...
}
```

As commenting this out restored the view.

**Comment by dado3212** [comment]
Sorry for the delay in merging this in, v1.7.2 should have this fix for everyone.  Thanks for flagging, and double thanks for tracking down the root cause!
