### ISSUE TITLE
Is there a way to achieve this programmatically?

### ISSUE THREAD

**Issue by jonathanlaniado** [dado3212/spaces-renamer#54]
I'd love to use Alfred or Keyboard Maestro to change the name of the `current desktop` on the fly, but I haven't found a way to retrieve the current desktop's UUID? Have you ever discovered how to retrieve that?

**Comment by jonathanlaniado** [comment]
In addition to that, any way I can trigger the window with a keyboard shortcut?

I've tried using AppleScript, but for whatever reason this clicks on the menu bar icon, but does not open the window.

```activate application "SpacesRenamer"
tell application "System Events"
    tell process "SpacesRenamer"
        click menu bar item 1 of menu bar 2
    end tell
end tell
```

**Comment by dado3212** [comment]
From the command line, this command will give you the current space's UUID (in the first monitor, not sure how this plays with multiple monitor setups).

`/usr/libexec/PlistBuddy -c "print :SpacesDisplayConfiguration:Management\ Data:Monitors:0:Current\ Space:uuid" ~/Library/Preferences/com.apple.spaces.plist`

If you're trying to programmatically do this, you're probably better off writing to the raw plist file than opening the window.  Not sure how to open the window with AppleScript 😕, but if you point me to an open source project that has support, I can see what I'm doing differently.

**Comment by jonathanlaniado** [comment]
Thanks Alex! See, I've come across a similar command to this, but both retrieve the leftmost desktop of the display, not the one that's currently being used (active desktop).

My use case is that if I create a new desktop, which by default is named Desktop #, I'd like to rename this new desktop, and to do that I need to get the UUID for that active desktop, not the leftmost one.

And I agree, if I can identify the current active desktop, then I could tell Alfred what to name it and work around using AppleScript.

**Comment by dado3212** [comment]
Ah, Spaces Renamer actually keeps track of it properly in the currentspaces.plist, which is how it knows which one to select when you open the window.  You can get at it with a slightly modified command as long as Spaces Renamer is installed: `/usr/libexec/PlistBuddy -c "print :Monitors:0:Current\ Space:uuid" ~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist`

**Comment by jonathanlaniado** [comment]
Uh-oh, looks like it's working... thank you! I will write a quick script tonight or this week and re-open if there are any issues. But this looks very promising. Thank you! 👊
