### ISSUE TITLE
Not changing desktop names on MacOS Sierra

### ISSUE THREAD

**Issue by AndreaCallia** [dado3212/spaces-renamer#57]
**Describe the bug**
The tool has been installed (from MacForge) and started, the menubar icon appears, but unfortunately whatever name I choose for the desktops, they are still called "Desktop 1", "Desktop 2", etc.

**Versions**
1. MySIMBL version - 0.14.2
2. Spaces Renamer version - 1.7.1

**Comment by dado3212** [comment]
Can you try version 1.7.3 (published recently), and confirm that you've done `pkill -9 Dock`?  Can you also paste the output of `csrutil status` from your command line?

**Comment by AndreaCallia** [comment]
Apparently it works if I run the mySIMBL app at least once every time I reboot the machine. Once mySIMBL is started at least once, even after closing it the app still works... many thanks for your support...

**Comment by dado3212** [comment]
You should be able to add mySIMBL to startup.  Also, if MacForge supports Sierra, that's a better alternative.  Marking as closed!
