### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by aagerblad** [dado3212/spaces-renamer#60]
**Describe the bug**
After a restart the plugin stopped working. I've tried all of the steps I usually do, and done a full reinstall of the plugin.

Everything is disabled:
![image](https://user-images.githubusercontent.com/1576086/86591522-0cda8780-bf92-11ea-94e2-6c67b04efa5a.png)

I've run `killall -9 Dock`

**Versions**
1. MacForge version - 0.14.2
2. Spaces Renamer version - 1.7.4
3. MacOS version - 10.15.5

No idea what else to try now.

**Comment by aagerblad** [comment]
For some reason it started working again. The only thing I did was install another completely unrelated plugin on MacForge.

Feel free to close this, but keep in mind that there's something weird happening.

**Comment by dado3212** [comment]
Hard to diagnose if it stops reproing, but comment on this if it reappears again!
