### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by w0lfschild** [dado3212/spaces-renamer#61]
**Describe the bug**

Doesn't work on Big Sur. The layer tree has changed. 
Fixed here : https://github.com/dado3212/spaces-renamer/pull/62

**Versions**
1. MacForge version - beta
2. Spaces Renamer version - 1.7.4

**Comment by dado3212** [comment]
<3 Thanks for the pull request.

**Comment by dado3212** [comment]
Resolved by PR #62, new v1.8.1 release created as an official release, so marking this as closed.  Thanks again 🎉
