### ISSUE TITLE
Dock crashes on hover

### ISSUE THREAD

**Issue by eli-byers** [dado3212/spaces-renamer#64]
First, thanks for making this, it's awesome! 

Here is when the problem occurs:

I activate control center with my mouse NOT at the top of my screen (somewhere bellow the 'spaces' bar).
I hover oven the spaces bar to expand and pick a space, Dock crashes and I'm back at my desktop. I checked Activity Monitor and Dock is definitely crashing when I hover over the bar.

Here is when the problem does NOT occur:

I activate control center with my mouse already at the top of my screen, and it activates with the space bar expanded.

MacOS Version 10.14.6, also I partially disabled SIP as outlined in the README.

I grabbed the Dock crash log from the Console:

Dock	*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; 0 nan]'

More crash log bellow:

`
Process:               Dock [1758]
Path:                  /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock
Identifier:            com.apple.dock
Version:               1.8 (1963.6)
Build Info:            Dock-1963006000000000~18
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Dock [1758]
User ID:               2147015034

Date/Time:             2020-07-21 20:23:00.214 -0700
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)
Anonymous UUID:        58CC0A4F-302C-9B46-1935-F9D4CC656F4F

Time Awake Since Boot: 320 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

External Modification Warnings:
Thread creation by external task.

Application Specific Information:
dyld3 mode
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; 0 nan]'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff361dbacd __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff608baa17 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff361db8ff +[NSException raise:format:] + 201
3   QuartzCore                          0x00007fff40ba0cf4 _ZN2CA5Layer10set_boundsERKNS_4RectEb + 194
4   QuartzCore                          0x00007fff40ba0c10 -[CALayer setBounds:] + 254
5   spaces-renamer                      0x0000000106a361ea -[_SRCALayer setBounds:] + 106
6   QuartzCore                          0x00007fff40ba37d7 -[CALayer setFrame:] + 642
7   spaces-renamer                      0x0000000106a36662 -[_SRCALayer setFrame:] + 1138
8   spaces-renamer                      0x0000000106a37f5e refreshFrames + 286
9   spaces-renamer                      0x0000000106a37f8e refreshFrames + 334
10  spaces-renamer                      0x0000000106a37f8e refreshFrames + 334
11  spaces-renamer                      0x0000000106a374fa -[_SRECMaterialLayer setFrame:] + 2474
12  Dock                                0x0000000104ab46b9 Dock + 1709753
13  Dock                                0x0000000104ab5e63 Dock + 1715811
14  Dock                                0x0000000104ab5f8b Dock + 1716107
15  Dock                                0x0000000104ab5d34 Dock + 1715508
16  Dock                                0x0000000104bf2756 Dock + 3012438
17  Dock                                0x0000000104bd8962 Dock + 2906466
18  Dock                                0x0000000104bd9ed9 Dock + 2911961
19  Dock                                0x0000000104b0cbc4 Dock + 2071492
20  Dock                                0x0000000104b0cc08 Dock + 2071560
21  Dock                                0x0000000104964b79 Dock + 334713
22  Dock                                0x0000000104963f40 Dock + 331584
23  Dock                                0x0000000104a0f9a4 Dock + 1034660
24  Dock                                0x0000000104bd8551 Dock + 2905425
25  Dock                                0x0000000104c12595 Dock + 3143061
26  Dock                                0x0000000104c128a6 Dock + 3143846
27  Dock                                0x000000010493563a Dock + 140858
28  HIServices                          0x00007fff34902771 mshPerform + 11
29  CoreFoundation                      0x00007fff3613d347 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
30  CoreFoundation                      0x00007fff3613d2a5 __CFRunLoopDoSource1 + 527
31  CoreFoundation                      0x00007fff3612529c __CFRunLoopRun + 2524
32  CoreFoundation                      0x00007fff3612466e CFRunLoopRunSpecific + 455
33  Dock                                0x0000000104aa3193 Dock + 1638803
34  Dock                                0x0000000104aa300e Dock + 1638414
35  libswiftObjectiveC.dylib            0x00007fff61d98f4f $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 47
36  Dock                                0x0000000104aa3073 Dock + 1638515
37  Dock                                0x0000000104aa2b3e Dock + 1637182
38  libswiftObjectiveC.dylib            0x00007fff61d98f4f $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 47
39  Dock                                0x0000000104918747 Dock + 22343
40  libdyld.dylib                       0x00007fff620893d5 start + 1

`

**Comment by dado3212** [comment]
> I activate control center with my mouse NOT at the top of my screen

How are you activating control center your mouse not at the top of your screen?  Finding it had to repro this.

**Comment by eli-byers** [comment]
I use the swipe gesture for Mission Control.

**Comment by dado3212** [comment]
Ah, repro'd this by setting a space name to a space character. Let me take a look.

**Comment by dado3212** [comment]
Should be resolved by v1.9.0, let me know if that resolves the issue.  If not, please open a new task, thank you!
