### ISSUE TITLE
Spaces not renamed after restart

### ISSUE THREAD

**Issue by cparasch123** [dado3212/spaces-renamer#65]
**Describe the bug**
I installed Spaces Renamer and named all spaces.  It worked.
I restarted my computer.
The names appear in the Spaces Renamer boxes (and the computer remembers them from before rebooting)

![Screen Shot 2020-08-28 at 12 25 24 PM](https://user-images.githubusercontent.com/70392222/91590597-9d499e80-e929-11ea-80d5-ee4750b4385f.png)

They do not appear on my screen, through Mission Control.

![Screen Shot 2020-08-28 at 12 25 30 PM](https://user-images.githubusercontent.com/70392222/91590619-a20e5280-e929-11ea-9e4e-6ac8605c99ac.png)

I tried both by having the app automatically open on launch, 
And by having it manually launch through Finder.

Both attempts to access the app and rename my spaces result in the same behaviour (spaces appear in Spaces Renamer, but names are not reflected in Mission Control)

**Versions**
1. MySIMBL version - 
2. Spaces Renamer version - Latest version (downloaded yesterday)

**Comment by itskando** [comment]
+1.

MacForge 1.0.7 (latest)
Spaces Renamer 1.7.1 (latest)

macOS 10.15.5 (10.15.6 is latest..)

**Comment by itskando** [comment]
Also, do I have anything to fear about the ominous warnings:

![image](https://user-images.githubusercontent.com/15063663/91783131-2a605200-ebcd-11ea-8eec-8bf01704b391.png)

**Comment by itskando** [comment]
![image](https://user-images.githubusercontent.com/15063663/91783279-b5414c80-ebcd-11ea-852d-23dd6df1b6ff.png)

**Comment by itskando** [comment]
MacForge discord (@w0lf - maybe @w0lfschild on here?) confirmed that plugins are loading with AfloatX.

Accessibility items running are insignificant:
(Scoll+hotkey = zoom, mouse/trackpad: springload delay).

Would any of these services interfere:
• hyperswitch
• hyperdock
• alfred

**Comment by sundaycrunk** [comment]
+1 All latest...

**Comment by itskando** [comment]
Seems to have resolved itself:

Mac died from battery loss.
By the time I got access to plug, started up from scratch.
Turned on MacForge. 
MacForge Update tab noted 1 update available — for spaces-renamer.
Clicking update button failed to do anything.
Went to spaces-renamer in Featured tab.
Mouse hover showed Up-facing Arrow.
Clicked — the plugin appeared instantly in an otherwise empty /Library/Application Support/MacForge/Plugins/

Plugin worked fine therein.

**Comment by dado3212** [comment]
Looks like this is resolved? Make sure you're following the installation instructions on here, and have the latest version.
