### ISSUE TITLE
Feature Request: Window width

### ISSUE THREAD

**Issue by itskando** [dado3212/spaces-renamer#66]
Can the default width of the Spaces Renamer app window 
equal the width of the active monitor/screen?

Using the whole width instead of half (the present value)
would allow more cases where most of the Spaces 
are not at all hidden beyond the app frame.

Plus scrolling still available when surpassing that, obviously.

.

A cool effect is that generally, 
Spaces in the renamer-app window could be centered 
to approximately line up with the 
Spaces in official mission control window :D 

.

**Versions**
Spaces Renamer version - 1.8.1

**Comment by itskando** [comment]
Updated description.

**Comment by dado3212** [comment]
Added this in in v1.9.0.  It'll try and take advantage of full screen width (previously it maxed at showing 6.5).

**Comment by itskando** [comment]
(No close until I send <3):

♥️♥️♥️
