### ISSUE TITLE
Feature Request - Space name in Menu Bar

### ISSUE THREAD

**Issue by JohnLockeNJ** [dado3212/spaces-renamer#68]
It would be really great to have an option for the name of the current space to be displayed in the menu bar.

**Comment by dado3212** [comment]
Duplicate of #5.

> Unfortunately Apple doesn't allow you to customize menu bar icons for different monitors, so this would break multi-monitor support.

**Comment by Flexperte** [comment]
Maybe have two (or more) menu bar icons, one for each monitor? 
Either by running two separate instances, or by making a larger icon like SpaceID does. 

Would be really nice, between WhichSpace, SpaceID and Spaces-Renamer to have one utility that combines their features.
