### ISSUE TITLE
Best means to update

### ISSUE THREAD

**Issue by itskando** [dado3212/spaces-renamer#70]
You're running 1.9.0 but MacForge is only offering 1.8.1.

Should I wait for MacForge or is there a quicker means to update?

.

**Versions**
Spaces Renamer version - 1.8.1

**Comment by itskando** [comment]
Downloaded and unzipped Build.
Quit and replaced the .app (in Applications) and the .bundle (location revealed by MacForge).
MacForge had no complaints and it the update looks great! Many thanks ~

**Comment by dado3212** [comment]
@w0lfschild How does the update system for MacForge work?  Do you manually update them?

**Comment by w0lfschild** [comment]
It gets the latest version from here:

https://github.com/MacEnhance/MacForgeRepo
