### ISSUE TITLE
Spaces Renamer doesn't show names on just laptop

### ISSUE THREAD

**Issue by jeffrhall24** [dado3212/spaces-renamer#71]
I just got spaces re-namer installed and I really like it! Thank you for creating it, it is very useful.

My question is on my laptop, when I go to mission control, all the names disappear unless I hover over that space. However, when I am hooked up to my two external monitors, when I go to mission control, all the names show fine, even when I'm hovering over them the other's show.

If it means anything, I am using better touch tool and their setting that immediately shows the desktop previews when going into mission control, which works fine when external monitors are hooked up.

If I just trigger mission control (without better touch tools's special setting to immediately show desktop preview), it shows the space names, but then when I go hover over them, the names disappear when I'm on my laptop and not hooked up to any external monitors.

Any idea on how I can fix this so the spaces show on my standalone laptop all the time?**Describe the bug**

**Versions**
1. MySIMBL version - Unsure
2. Spaces Renamer version - 1.9.0

**Comment by dado3212** [comment]
Hey @jeffrhall24! Could you upload a video of the bug? In Mission Control the names don't appear unless you hover if you have too many spaces (I think it's around 11 or something that it starts doing this). That's default Mac behavior though. My guess is that you have 11+ spaces, where some are on your personal laptop, and some are on your external monitors. When the external monitors are connected, each monitor has 10 or fewer, so they render all of the names. When you disconnect, they all appear on your laptop though, going into the default "hide until you hover" state. The hovering is to allow the screen previews to shrink, so if that is the issue, I'd mark this as wontfix (not confident that there's an elegant way to handle it, and in general changing behavior of Expose is pretty hard with my current implementation).

**Comment by dado3212** [comment]
If this isn't the issue, feel free to comment or reopen!
