### ISSUE TITLE
Spaces Renamer Not Working After Updating to Big Sur

### ISSUE THREAD

**Issue by jeffrhall24** [dado3212/spaces-renamer#72]
I recently updated to Big Sur, and Spaces Renamer is not working. I even re-tried the steps in the macforge system app with the two terminal commands they require.

Any ideas on how to fix?

**Describe the bug**

**Versions**
1. MySIMBL version - 
2. Spaces Renamer version -

**Comment by nicholasandriy** [comment]
Can confirm, also have big sur and not matter what I try I cannot get it to work, unfortunately. I greatly miss this feature

**Comment by dado3212** [comment]
@jeffrhall24, @nicholasandriy 
This should be resolved by v1.9.1. If either of you are still running into problems, please file a new issue!
