### ISSUE TITLE
Cannot Identify Monitors when using muti-monitors and each monitor has the same number of  desktops

### ISSUE THREAD

**Issue by xihangzhou** [dado3212/spaces-renamer#80]
**Describe the bug**
when using muti-monitors and each monitor has the same number of  desktops, the name that I give to monitor2 would be displayed on monitor1.

**Versions**
1. MySIMBL version - 1.1.0
2. Spaces Renamer version - 1.9.1

**Comment by dado3212** [comment]
Yeah, this is a KP. I think there's no great API for differentiating between the monitors. The code does it's best at trying to guess based on the number of spaces, and also based on it's memory of which monitor is which. It's possible that if you add one desktop to one of them, fix the names, and then remove that added desktop that it will keep track, alternatively you can just create a desktop which doesn't do anything to make sure they have different numbers. Will leave this issue open for now in case anyone has ideas, but I haven't been able to find a way to make this work.

**Comment by dado3212** [comment]
Should be fixed by 1.11.1.
