### ISSUE TITLE
Use two monitors, on 1 of the monitors, there are 5 spaces in Renamer, only 4 on my OS

### ISSUE THREAD

**Issue by dennisrcao** [dado3212/spaces-renamer#81]
<img width="723" alt="Screen Shot 2022-02-24 at 8 32 10 PM" src="https://user-images.githubusercontent.com/521934/155654169-228e15a6-4973-4697-bd5f-80584bf8b042.png">
<img width="990" alt="Screen Shot 2022-02-24 at 8 32 01 PM" src="https://user-images.githubusercontent.com/521934/155654176-8defe08a-440c-4655-800c-1866642a2a2d.png">

The Renamer thinks there are 5 total spaces, but I only have access to 4

**Comment by dado3212** [comment]
I think it’s probably out of sync. If you quit SpacesRenamer and MacForge, delete `~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.plist` and `~/Library/Containers/com.alexbeals.spacesrenamer/com.alexbeals.spacesrenamer.currentspaces.plist` and restart, does that fix the issue?
