### ISSUE TITLE
Does not changes space names

### ISSUE THREAD

**Issue by JuliaRakitina** [dado3212/spaces-renamer#86]
**Describe the bug**  
Does not set space name and never do. I applied all recommendations. Nothing worked.

**Versions**  
1. MySIMBL version - NA
2. Spaces Renamer version -1.9.1
3. MacOS version - 12.3

**Command Outputs**  
Please paste the output of running these commands in Terminal:

* `julia             5877   0.0  0.0 36278012  28280   ??  S     4:36PM   0:00.62 /Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper
julia             4165   0.0  1.6 40162888 1050264   ??  S     4:35PM   0:15.27 /Applications/MacForge.app/Contents/MacOS/MacForge
root              2291   0.0  0.0 34274208   6168   ??  Ss    4:30PM   0:00.04 /Library/PrivilegedHelperTools/com.macenhance.MacForge.Injector`
* `julia             5929   0.0  0.1 36270008  72852   ??  S     4:36PM   0:01.08 /Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer`
* `System Integrity Protection status: disabled.`
<img width="930" alt="Screen Shot 2022-03-26 at 16 30 59" src="https://user-images.githubusercontent.com/4850840/160239998-aee7be7f-be12-4132-8ee8-4d626b6f6d70.png">
<img width="612" alt="Screen Shot 2022-03-26 at 16 32 42" src="https://user-images.githubusercontent.com/4850840/160240002-e8856691-bd17-468c-98b9-60ee48a23c33.png">
<img width="377" alt="Screen Shot 2022-03-26 at 16 33 06" src="https://user-images.githubusercontent.com/4850840/160240003-82a50687-93df-425b-b8e6-05056fb25b60.png">
<img width="582" alt="Screen Shot 2022-03-26 at 16 33 20" src="https://user-images.githubusercontent.com/4850840/160240004-1765df84-62d5-48eb-a75d-d7c2a58f767f.png">

**Comment by JuliaRakitina** [comment]
Reduce transparency is turned off

**Comment by ChristianTraxler** [comment]
Yes I can't seem to get it to work as well. However, I am using a M1 Mac. Is there going to be an update to work with this?

**Comment by dennisrcao** [comment]
Got the same issue here.

**Comment by richjames0** [comment]
Sadly I'm having this issue too. Would be happy to work with you to debug it, as it'd be *amazing* to have this working :)

**Comment by tacomania** [comment]
Same issue but I'm on Ventura.  Hope to resolve!  I've had this working on past machines and LOVE it.

**Comment by pedroponte** [comment]
same here, also on ventura

**Comment by spacemudd** [comment]
Opened MacForge, disabled and then renabled the plugin. Then opened Spacerenamer. It worked.

**Comment by leblaze** [comment]
Not working on M1 Ventura

**Comment by richjames0** [comment]
> Opened MacForge, disabled and then renabled the plugin. Then opened Spacerenamer. It worked.

Weirdly enough this worked for me too. What I did specifically
- Click on MacForge in menu bar
- Select Manage Plugins
- Search for Spaces renamer
- Clicked on its icon, not on open
- Clicked Remove
- Clicked Open

Thank you @spacemudd !

**Comment by geweihgg** [comment]
@richjames0 Hi, I met the same problem, so I tried your methods, but it doesn't work. I cannot find 'remove' there.

![image](https://github.com/dado3212/spaces-renamer/assets/18585014/71aff990-fa1d-43e8-b7c1-c6d7a984c0fe)

**Comment by richjames0** [comment]
@geweihgg Sadly I can no longer get it working on a new M1 Mac :( 

The UI has changed but the equivalent of Remove is presumably Trash or possibly unticking the box, but even with that I can't make it work

**Comment by spiritually-soup** [comment]
MacOS Monterey 12.6.6

It doesn't work for me either.... and the `update` button is greyed out.
<img width="1323" alt="image" src="https://github.com/dado3212/spaces-renamer/assets/92115028/3a93bd06-9e79-40b6-aef0-28d6990f14b2">

Nothing appears  under `Manage Plugins` either, despite having the bundle in the correct folder when I checked :(
<img width="1000" alt="image" src="https://github.com/dado3212/spaces-renamer/assets/92115028/afcb49dd-b2b7-4600-b884-7b9c04d6b528">
<img width="382" alt="image" src="https://github.com/dado3212/spaces-renamer/assets/92115028/1f4ecd4c-d0a6-4d05-ad49-9aab6d1e40c7">

**Comment by dado3212** [comment]
Closing this issue, most of this should be handled by the special Apple Silicon install instructions. If people are running into new issues, please open a new task!
