### ISSUE TITLE
Spaces-Renamer.app does not show any window when started

### ISSUE THREAD

**Issue by marcwimmer** [dado3212/spaces-renamer#87]
**Describe the bug**  
When i start spacesrenamer.app nothing happens. I dont see any window popping up.
I have a green light in macforge next to the plugin.

**Versions**  
1. MacFroge 1.20.1 beta version - 
2. Spaces Renamer 1.10.3 -
3. MacOS version - 12.3.1 M1 

**Command Outputs**  
Please paste the output of running these commands in Terminal:

* `ps aux | grep -v grep | grep -i macforge`
marcwimmer        7464   0.4  1.6 413250432 1081600   ??  S     8:10PM   0:15.45 /Users/marcwimmer/Applications/MacForge.app/Contents/MacOS/MacForge
root              2328   0.0  0.0 34355056   5940   ??  Ss    7:54PM   0:00.07 /Library/PrivilegedHelperTools/com.macenhance.MacForge.Injector
marcwimmer        7489   0.0  0.1 409675472  38448   ??  S     8:10PM   0:00.58 /Users/marcwimmer/Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper

* `ps aux | grep -v grep | grep -i spacesrenamer`
<empty>

* `csrutil status`:
System Integrity Protection status: disabled.

**Comment by dado3212** [comment]
This is expected behavior, no window is supposed to show up. It should create an icon in the top bar that you can click to open the UI for renaming spaces.
