### ISSUE TITLE
MacOS 14 "Sonoma" status?

### ISSUE THREAD

**Issue by jvthomas90** [dado3212/spaces-renamer#93]
Sorry, this isn't a bug report, more of a timely question. I'd happily open a discussion topic if I could but that's not an option on this repo. Thought about posting on #75 but I saw that it was closed ~2 weeks ago with the ReadMe.md update. Apologies for opening a new ticket, I didn't know where else to ask this.

TL;DR I'm aware that Spaces Renamer works on macOS 13 "Ventura" as well and I can confirm that the proposed workaround method runs like a dream on my M2 Air. My question is... what about the recently released and latest OS version 14 "Sonoma"?

Just a friendly headsup, MacForge [v 1.2.2 beta 2](https://github.com/jslegendre/appcast/blob/master/Beta/MacForge/MacForge.1.2.2-2.zip) works fine on Ventura and Sonoma. Likewise, a number of the plugins like AfloatX, moreMenu, GoodBye, MiniMe, ColorfulSidebarX, IconChamp, cDock etc have all been updated for the latest OS and seem to run smoothly. 

I'm not sure why MacEnhance.com hasn't been updated with the latest info, but he's been quite responsive and open on Discord over the course of many months about bugfixes and compatibility updates right up until Sonoma was released. Heck, in the case of cDock v5 forget about their site it's not even being reflected on the MacForge store like all the rest - nevertheless it's available [here](https://github.com/jslegendre/appcast/blob/master/Beta/cDock/cDock.5.1.3.zip) and the dev has "psuedo-officially" confirmed that it runs like clockwork on the latest Sonoma release _(I say "psuedo-officially" because, while it's not being reflected on the official site or storefront yet for some reason, the confirmation news is coming straight from the proverbial horse's mouth i.e. Jeremy on the official MacEnhance Discord server)_

Sorry, took a bit of a tanget there lol, but the point is **A** Sonoma updates are rolling in, both for MacForge as well as MacForge plugins (at least, so far, those made by MacEnhance/Jeremy), **B** all of these are available for public testing up on his GitHub and **C** he's seems to be available and responsive on Discord if there's a need for follow up questions or clarification.

I realize that you're a 3rd party dev, but all the necessary pieces seem to be present, so... any plans on updating Spaces Renamer for Sonoma? 🤞🏽 Or is it already compatible?? Everyone discussing M-Series compatibility on #75 only mentioned Ventura, and I searched the repo but didn't see any keywords like "macOS 14" or "Sonoma" etc being mentioned anywhere in Issues, Pull Requests, Releases, etc 🥲 

FYI, the only 3 plugins I currently have enabled are Spaces Renamer, AfloatX and cDock - and the latter 2 have since been subsequently updated for Sonoma, meaning Spaces Renamer is pretty much the only thing holding me back from updating 😂 I've used tools like TotalSpaces, CurrentKey Stats, Space Capsule, SpaceMan, SpaceID, Contexts, etc etc in the past. Spaces Renamer has been the only one that's ever felt "seamless" and "native" to me. So... `#prettyplease` consider updating for the latest OS? 🥺 My intuition tells me that since the MacForge injection method and platform itself, as well as various plugins too, have already been updated accordingly this shouldn't be too difficult a solve – but I'm not a coder so I recognize that my intuitions are probably meaningless 😅 Still, I wanted to ask / give you a headsup on all this anyway, just in case you weren't aware!

**Comment by dado3212** [comment]
I have no idea if it works on Sonoma, I'm personally still on Ventura 13.6. But there hasn't really been a necessary update in a while, the only thing was the architecture change for the Apple Silicon devices. My suspicion is that it should already work.

**Comment by jvthomas90** [comment]
Well, that's somewhat reassuring :) `sigh` Alright, guess I'll be the guinea pig and test it out in new waters! 😅 

I've been meaning to migrate data to my external drive and do a clean wipe of my machine before installing Sonoma, so it isn't a simple hands-off/overnight procedure for me to update. I'll probably wait till this weekend to set aside some time and get all that done. 

Will install Spaces Renamer soon thereafter and report back my findings! 👍🏽

**Comment by jvthomas90** [comment]
Couldn't do the update last weekend as planned but I just got around to it, aaand... everything seems to work well out-of-the-box so far :)

Still, this is a fresh install. I'll spend the rest of the day testing out the new OS whilst keeping an eye on my Mac Spaces + Spaces Renamer to see if they change/update/mirror each other and it all stays in sync, that there aren't any unexpected bugs or glitches after prolonged usage, etc etc. 

It's Friday noon right now, if I haven't noticed anything by the time the weekend is over feel free to close this ticket. Even if I do notice some edge-case issue at a later point I'll just continue to comment on here or open a new ticket dedicated to that particular bug.

I originally opened this thread in the hopes of ascertaining if there are any **breaking changes** though, so if I run into any of those in the next few days I'll definitely let you know on here ASAP. If not though, I figure I can just report on any minor bugs or other odd/quirky (but still functional) behavior that needs fixing elsewhere on it's own ticket.

But anyway, TL;DR is so far so good! At first glance, it doesn't seem like any particular changes are required for Spaces Renamer to keep working as expected even after the Sonoma update :D

**Comment by Fred-DTV** [comment]
I unfortunetly can't get it working on Sonoma :/

Tried through the 1.2.0 official MacForge release as well as through the 1.2.2 beta both times with re-installing space renamer.
It shows up in the taskbar and I can use the pop up window to enter names for the spaces (it even recognizes the correct number of spaces) but it doesn't rename the spaces.
SIP and everything else is turned off.

Is there a log somewhere which I could post to help?

**Comment by dado3212** [comment]
@Fred-DTV please file a new task, it will have debugging instructions automatically as part of the template.

**Comment by Fred-DTV** [comment]
Hope this helps:

```
Fred@FredBook-Pro ~ % ps aux | grep -v grep | grep -i macforge
Fred              1077   0.0  0.1 410095232  37024   ??  S    Sun10PM   0:03.64 /Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper
Fred@FredBook-Pro ~ % ps aux | grep -v grep | grep -i spacesrenamer
Fred              1071   0.0  0.0 35764792  13000   ??  S    Sun10PM   0:01.86 /Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer
Fred@FredBook-Pro ~ % csrutil status
System Integrity Protection status: disabled.
```

**Comment by izaankml** [comment]
Having the same issue on Sonoma, can get to the pop up window where I can rename spaces (although I'm always seeing one space more than i have open) but entering new names and hitting update doesn't change anything.

**Comment by dado3212** [comment]
Please file a new task.
