### ISSUE TITLE
Sonoma 14.4.1, SpacesRenamer not working

### ISSUE THREAD

**Issue by falquaddoomi** [dado3212/spaces-renamer#96]
**Describe the bug**  
On my Macbook M1 Pro (14-inch, 2021 model), SpacesRenamer and MacForge were working fine in Sonoma, using the M1 installation instructions from the readme. After to upgrading to Sonoma 14.4.1, neither MacForge nor SpacesRenamer report any issues, but the desktops simply don't get renamed. I currently have SIP disabled entirely, although I'll probably go back to disabling specific parts of it once things settle down. I followed some directions from issue #95, which is why I'm on MacForge 1.2.2 (2), but to no avail.

(I realize there's already a bug report for Sonoma, but I thought I'd submit one with the fields from the bug report template filled out. I hope this isn't causing additional load on the people who support this project, and thanks for all your work.)

**Versions**  
1. MySIMBL version - MacForge 1.2.2 (2)
2. Spaces Renamer version - 1.10.4
3. MacOS version - 14.4.1 (23E224)

**Command Outputs**  
Please paste the output of running these commands in Terminal:

* `ps aux | grep -v grep | grep -i macforge`
```shell
faisala           8476   0.0  0.1 412188320  44960   ??  S    11:25AM   0:00.23 /Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper
faisala           8468   0.0  0.5 412572080 165856   ??  S    11:25AM   0:02.10 /Applications/MacForge.app/Contents/MacOS/MacForge
```
* `ps aux | grep -v grep | grep -i spacesrenamer`
```shell
faisala          10751   0.0  0.2 35373536  54112   ??  S    11:30AM   0:01.37 /Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer
```
* `csrutil status`
```shell
System Integrity Protection status: disabled.
```

**Comment by dado3212** [comment]
Yup, the proposed fix in #95 doesn't work. Closing this to just track in #95, am reaching out to MacForge people to see what changed.
