### ISSUE TITLE
Not Working On OS X 14.3

### ISSUE THREAD

**Issue by doublezigzag** [dado3212/spaces-renamer#97]
on M1 running Sonoma 14.3. followed all instructions. only step that was not confirmed was step 6

"Copy the spaces-renamer.bundle version to /Library/Application Support/MacEnhance/Plugins"

there is no such folder. but there is "Users/Shared/MacEnhance/" , no plugins folder.

i moved it there but not sure this is right. 

the renamer icon does show up on the toolbar, and correctly identifies the NUMBER of spaces, but nothing happens when i click on "update names".

hoping i am missing something easy.

thanks!

**Comment by falquaddoomi** [comment]
Hey @doublezigzag, IIRC you need to run MacForge once and perhaps install a plugin before it'll create the `/Library/Application Support/MacEnhance/Plugins` folder. You can just install a random plugin and then delete it. Then, quit MacForge entirely, copy in the patched `spaces-renamer.bundle` file to `/Library/Application Support/MacEnhance/Plugins`, and then restart MacForge.

If you've done all that correctly, you should see something like this on MacForge's "Manage Plugins" page; note the green dot next to "Apple Silicon" and the version number, 1.10.4:
![Screenshot 2024-04-17 at 12 01 46 PM](https://github.com/dado3212/spaces-renamer/assets/312923/a326d649-bf7e-425a-9b07-4c2b13449795)

Hope that helps!

**Comment by dbykadorov** [comment]
@doublezigzag Did you get it working? On macos 14.2 I see spaces-renamer in plugis, but names still not changed...

<img width="1002" alt="image" src="https://github.com/dado3212/spaces-renamer/assets/243108/54ad6674-43bb-470b-90f6-d67830fbc58d">

<img width="319" alt="image" src="https://github.com/dado3212/spaces-renamer/assets/243108/7b6c6f76-3cbf-437b-86bb-25e52b93270d">

![image](https://github.com/dado3212/spaces-renamer/assets/243108/c17d1bb6-fa5b-4404-a3b6-412a9e52da67)

**Comment by dado3212** [comment]
Marking as closed, seems resolved.
