### ISSUE TITLE
Don't have a new icon in the to bar following install.

### ISSUE THREAD

**Issue by Etyre** [dado3212/spaces-renamer#98]
**Describe the bug**  

I just went through all the steps of the install process for Installation (M1/M2/Apple Silicon). 

I'm pretty sure every step worked. Macforge is working now. Spaces-renamer.bundle is in /Library/Application Support/MacEnhance/Plugins folder. When I run killall `-9 Dock`, the top bar flashes. 

But there's no new icon spaces renamer. (There was previously one for macforge as a whole, but it seems to be gone now.)

![Screenshot 2024-05-25 at 7 38 30 PM](https://github.com/dado3212/spaces-renamer/assets/23288300/856b7227-858c-4acd-9cc7-0e7c61c443f3)

Any suggestions?

**Versions**  
1. MySIMBL version - Not sure
2. Spaces Renamer version - Whatever the most recent one is.
3. MacOS version - 14.5 (23F79)

**Command Outputs**  
Please paste the output of running these commands in Terminal:

* `ps aux | grep -v grep | grep -i macforge`

```
7176   0.5  3.1 415001472 1045296   ??  S     7:24PM   0:20.62 /Users/elityre/Applications/MacForge.app/Contents/MacOS/MacForge
elityre           7190   0.0  0.2 411930720  74480   ??  S     7:24PM   0:01.86 /Users/elityre/Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper
```

* `ps aux | grep -v grep | grep -i spacesrenamer`

```
6693   0.0  0.1 35866452  18696   ??  S     7:18PM   0:00.55 /Users/elityre/Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer
elityre           7223   0.0  0.1 35505124  23724   ??  S     7:25PM   0:00.58 /Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer
```

* `csrutil status`

```
System Integrity Protection status: disabled.
```

**Comment by Etyre** [comment]
Oh. I think actually what I thought was the MacForge icon was actually the Spaces-renamer icon. However when I clicked on it, nothing happened. And in any case, it's not there now.

Any recommendations for how to get it back?

**Comment by dado3212** [comment]
This should only happen if there are too many icons in your menu bar. You can try to get rid of some (hold Command and drag them off) or maybe shrink the dock size? Not sure what the best way to address this is, Apple's UI for managing lots of Menu bar icons leaves a lot to be desired.

**Comment by dado3212** [comment]
See potential solutions here - https://github.com/dado3212/spaces-renamer/issues/94#issuecomment-2126843231.

**Comment by dado3212** [comment]
Added to debugging FAQ - https://github.com/dado3212/spaces-renamer/tree/master?tab=readme-ov-file#debugging-common-issues, closing issue.
